import { Document, Page, Text, pdf } from '@react-pdf/renderer';
import React from 'react';
import { DocumentSchema } from '../schemas/document';

// Simple PDF renderer without JSX compilation issues
export class SimpleRenderer {
  static async render(spec: any): Promise<Buffer> {
    try {
      // Validate
      const validated = DocumentSchema.parse(spec);
      
      // Create React elements using React.createElement instead of JSX
      const MyDocument = () => React.createElement(
        Document,
        null,
        React.createElement(
          Page,
          { size: 'A4', orientation: 'portrait' },
          React.createElement(
            Text,
            { 
              style: { 
                fontSize: 24, 
                textAlign: 'center', 
                marginTop: 100, 
                fontWeight: 'bold' 
              }
            },
            validated.props.title || 'PDF Document'
          ),
          React.createElement(
            Text,
            { 
              style: { 
                fontSize: 16, 
                textAlign: 'center', 
                marginTop: 30 
              }
            },
            'Author: ' + (validated.props.author || 'Unknown')
          ),
          React.createElement(
            Text,
            { 
              style: { 
                fontSize: 14, 
                textAlign: 'center', 
                marginTop: 20 
              }
            },
            'Subject: ' + (validated.props.subject || 'Document')
          ),
          React.createElement(
            Text,
            { 
              style: { 
                fontSize: 12, 
                textAlign: 'center', 
                marginTop: 50 
              }
            },
            'Pages: ' + (validated.children?.length || 1)
          ),
          React.createElement(
            Text,
            { 
              style: { 
                fontSize: 10, 
                textAlign: 'center', 
                marginTop: 100 
              }
            },
            'Generated by PDF AI Generator with Deepseek AI + JSON-Render + React-PDF'
          ),
          React.createElement(
            Text,
            { 
              style: { 
                fontSize: 10, 
                textAlign: 'center', 
                marginTop: 10 
              }
            },
            'Date: ' + new Date().toLocaleDateString()
          )
        )
      );
      
      // Generate PDF
      const instance = pdf(React.createElement(MyDocument));
      const buffer = await instance.toBuffer();
      
      return buffer;
      
    } catch (error: any) {
      console.error('PDF rendering error:', error);
      throw new Error('PDF rendering failed: ' + error.message);
    }
  }
}
