import { Document, Page, Text, View, pdf } from '@react-pdf/renderer';
import { DocumentSchema } from '../schemas/document';

// Simple but working PDF renderer
export class WorkingRenderer {
  static async render(spec: any): Promise<Buffer> {
    try {
      // Validate
      const validated = DocumentSchema.parse(spec);
      
      // Create simple PDF
      const MyDocument = () => (
        <Document>
          <Page size="A4" orientation="portrait">
            <Text style={{ fontSize: 24, textAlign: 'center', marginTop: 100, fontWeight: 'bold' }}>
              {validated.props.title || 'PDF Document'}
            </Text>
            <Text style={{ fontSize: 16, textAlign: 'center', marginTop: 30 }}>
              Author: {validated.props.author || 'Unknown'}
            </Text>
            <Text style={{ fontSize: 14, textAlign: 'center', marginTop: 20 }}>
              Subject: {validated.props.subject || 'Document'}
            </Text>
            <Text style={{ fontSize: 12, textAlign: 'center', marginTop: 50 }}>
              Pages: {validated.children?.length || 1}
            </Text>
            <Text style={{ fontSize: 10, textAlign: 'center', marginTop: 100 }}>
              Generated by PDF AI Generator with Deepseek AI + JSON-Render + React-PDF
            </Text>
            <Text style={{ fontSize: 10, textAlign: 'center', marginTop: 10 }}>
              Date: {new Date().toLocaleDateString()}
            </Text>
          </Page>
        </Document>
      );
      
      // Generate PDF
      const instance = pdf(<MyDocument /> as any);
      const buffer = await instance.toBuffer();
      
      return buffer;
      
    } catch (error: any) {
      console.error('PDF rendering error:', error);
      throw new Error('PDF rendering failed: ' + error.message);
    }
  }
}
